name: githubactions_new_file

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'greet the person'
        required: true
        default: 'World'
##jobs
jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
      - name: give the greeting
        run: echo "Hello ${{ github.event.inputs.name }}"
