name: githubactions_new_file

on:
    workflow_dispatch:
        inputs:
            description: 'greet the person'
            default: 'World'
            required: 'true'
            
jobs:
    greeting:
        runs-on: ubuntu-latest
        
        steps:
            - name: give the greeting
              run: echo "Hello ${{ github.event.inputs.name}}"
                
  
